#!/bin/sh

#abort if `current conf` != `production.checkout` ==> ERROR: current configuration differs deployment management info

#abort if `/opt/cob-cli.checkout/ACTIVE_VERSION` != "master" ==> ERROR: current configuration set to `echo ACTIVE_VERSION`